---
output:
  html_document:
    keep_md: yes
---

### ADMM

`ADMM` is an R package to solve Lasso-like problems using the ADMM algorithm.

### Comparison

Comparing `ADMM` with `glmnet`

```{r}
library(glmnet)
library(ADMM)
set.seed(123)
n <- 100
p <- 20
m <- 5
b <- matrix(c(runif(m), rep(0, p - m)))
x <- matrix(rnorm(n * p, mean = 1.2, sd = 2), n, p)
y <- 5 + x %*% b + rnorm(n)

## standardize = TRUE, intercept = TRUE
fit <- glmnet(x, y)
out_glmnet <- coef(fit, s = exp(-2), exact = TRUE)
out_admm <- admm_lasso(x, y, exp(-2))
out_paradmm <- admm_parlasso(x, y, exp(-2))
data.frame(glmnet = as.numeric(out_glmnet),
           admm = as.numeric(out_admm$beta),
           paradmm = as.numeric(out_paradmm$beta))

## standardize = TRUE, intercept = FALSE
fit2 <- glmnet(x, y, intercept = FALSE)
out_glmnet2 <- coef(fit2, s = exp(-2), exact = TRUE)
out_admm2 <- admm_lasso(x, y, exp(-2), intercept = FALSE)
out_paradmm2 <- admm_parlasso(x, y, exp(-2), intercept = FALSE)
data.frame(glmnet = as.numeric(out_glmnet2),
           admm = as.numeric(out_admm2$beta),
           paradmm = as.numeric(out_paradmm2$beta))

## standardize = FALSE, intercept = TRUE
fit3 <- glmnet(x, y, standardize = FALSE)
out_glmnet3 <- coef(fit3, s = exp(-2), exact = TRUE)
out_admm3 <- admm_lasso(x, y, exp(-2), standardize = FALSE)
out_paradmm3 <- admm_parlasso(x, y, exp(-2), standardize = FALSE)
data.frame(glmnet = as.numeric(out_glmnet3),
           admm = as.numeric(out_admm3$beta),
           paradmm = as.numeric(out_paradmm3$beta))

## standardize = FALSE, intercept = FALSE
fit4 <- glmnet(x, y, standardize = FALSE, intercept = FALSE)
out_glmnet4 <- coef(fit4, s = exp(-2), exact = TRUE)
out_admm4 <- admm_lasso(x, y, exp(-2), standardize = FALSE, intercept = FALSE)
out_paradmm4 <- admm_parlasso(x, y, exp(-2), standardize = FALSE, intercept = FALSE)
data.frame(glmnet = as.numeric(out_glmnet4),
           admm = as.numeric(out_admm4$beta),
           paradmm = as.numeric(out_paradmm4$beta))
```

### rho setting

```{r eval=FALSE}
lambda <- exp(-2)
rho_ratio <- exp(seq(log(0.1), log(10), length.out = 100))
niter <- sapply(rho_ratio,
    function(r) admm_lasso(x, y, lambda, opts = list(rho_ratio = r))$niter
)
plot(rho_ratio, niter)
```

### Performance

```{r}
# compute the full solution path, n > p
set.seed(123)
n <- 50000
p <- 1000
m <- 100
b <- matrix(c(runif(m), rep(0, p - m)))
x <- matrix(rnorm(n * p, sd = 2), n, p)
y <- x %*% b + rnorm(n)

system.time(res1 <- glmnet(x, y, nlambda = 20))
system.time(res2 <- admm_lasso(x, y, nlambda = 20))
system.time(res3 <- admm_parlasso(x, y, nlambda = 20))

nlam = length(res1$lambda)
res2$niter
range(coef(res1) - res2$beta[, 1:nlam])
res3$niter
range(coef(res1) - res3$beta[, 1:nlam])

# p > n, single lambda
set.seed(123)
n <- 2000
p <- 10000
m <- 100
b <- matrix(c(runif(m), rep(0, p - m)))
x <- matrix(rnorm(n * p, sd = 2), n, p)
y <- x %*% b + rnorm(n)

system.time(res1 <- glmnet(x, y, nlambda = 20))
system.time(res2 <- admm_lasso(x, y, nlambda = 20))
system.time(res3 <- admm_parlasso(x, y, nlambda = 20))

nlam = length(res1$lambda)
res2$niter
range(coef(res1) - res2$beta[, 1:nlam])
res3$niter
range(coef(res1) - res3$beta[, 1:nlam])
```

### rho setting

```{r eval=FALSE}
lambda <- exp(-2)
rho_ratio <- exp(seq(log(0.1), log(10), length.out = 100))
niter <- sapply(rho_ratio,
    function(r) admm_lasso(x, y, lambda, opts = list(rho_ratio = r))$niter
)
plot(rho_ratio, niter)
```
